#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
source "$PLUGIN_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

PADDINGS=3 # All paddings use this value (icon, label, background and bar paddings)
FONT="Hack Nerd Font"

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

# Setting up the general bar appearance and default values
sketchybar --bar height=40 \
  corner_radius=9 \
  border_width=0 \
  margin=10 \
  blur_radius=50 \
  position=top \
  padding_left=10 \
  padding_right=10 \
  color=$BASE \
  topmost=off \
  sticky=on \
  font_smoothing=off \
  y_offset=10 \
  shadow=$SURFACE0 \
  notch_width=200 \
  \
  --default drawing=on \
  updates=when_shown \
  label.font="$FONT:Regular:17.0" \
  icon.font="$FONT:Bold:17.0" \
  icon.color=$TEXT \
  label.color=$TEXT \
  icon.padding_left=$PADDINGS \
  icon.padding_right=$PADDINGS \
  label.padding_left=$PADDINGS \
  label.padding_right=$PADDINGS \
  background.padding_right=$PADDINGS \
  background.padding_left=$PADDINGS \
  background.height=28 \
  popup.background.border_width=$POPUP_BORDER_WIDTH \
  popup.background.corner_radius=$POPUP_CORNER_RADIUS \
  popup.background.border_color=$POPUP_BORDER_COLOR \
  popup.background.color=$BASE \
  popup.background.shadow.drawing=$SURFACE0
sketchybar --add event aerospace_workspace_change
# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
sketchybar --add item clock right \
  --set clock update_freq=10 \
  icon= \
  icon.color=$YELLOW \
  script="$PLUGIN_DIR/clock.sh" \
  background.corner_radius=6 \
  background.padding_left=8 \
  background.padding_right=8
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
